---
services:
  runner:
    image: thevickypedia/github-runner-linux
    build:
      context: .
    restart: always
    # env_file: '.env'
    environment:
      GIT_TOKEN: ${GIT_TOKEN}
      GIT_OWNER: ${GIT_OWNER}
      GIT_REPOSITORY: ${GIT_REPOSITORY}
      RUNNER_GROUP: ${RUNNER_GROUP}
      RUNNER_NAME: ${RUNNER_NAME}
      WORK_DIR: ${WORK_DIR}
      LABELS: ${LABELS}
      REUSE_EXISTING: true
    container_name: github-runner-linux
    working_dir: /home/docker
