---
version: '3.8'

services:
  runner:
    image: runner:latest
    build:
      context: .
      args:
        RUNNER_VERSION: '2.319.1'
    environment:
      GIT_TOKEN: ${GIT_TOKEN}
      GIT_OWNER: ${GIT_OWNER}
      GIT_REPOSITORY: ${GIT_REPOSITORY}
      RUNNER_GROUP: ${RUNNER_GROUP}
      WORK_DIR: ${WORK_DIR}
      LABELS: ${LABELS}
