name: Test Runner

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: docker-node
    steps:
    - uses: actions/checkout@v4
    - name: Verify 'curl'
      run: curl --version
      shell: bash
    - name: Verify 'git'
      run: git --version
      shell: bash
    - name: Verify 'jq'
      run: jq --version
      shell: bash
    - name: Verify 'python'
      run: python -V
      shell: bash
    - name: Verify 'rustc'
      run: rustc --version
      shell: bash
    - name: Verify 'cargo'
      run: cargo --version
      shell: bash
    - name: Verify 'rustfmt'
      run: rustfmt --version
      shell: bash
    - name: Verify 'go'
      run: go version
      shell: bash
    - name: Verify 'node'
      run: node --version
      shell: bash
    - name: Verify 'npm'
      run: npm --version
      shell: bash
